### ISSUE TITLE
Console - wrong input bit order

### ISSUE THREAD

**Issue by zokl** [disk91/itsdk-example-sigfox-sx1276#1]
Hello,

Described console input for adding ID and KEY has wrong bit order. The shoved behavior is for SDK in the master branch. Branch Version-1.6 changes bit order. It will be good to add a note to the tutorial.

**Comment by disk91** [comment]
You right ! I missed that and checked it with master !
I'll push this important fix in branch 1.6 tonight

**Comment by disk91** [comment]
Master fix has been published in branch 1.6
You should not have this bug anymore.
Let me know is any other problem
